Added Trick manager
Sp4tz7/OC_P6 pull request #55
Opened 2020-11-05 16:35 UTC by Sp4tz7

Close #54

2020-11-06 08:43 UTC, Jduret commented on src/Service/Trick/Manager/TrickManager.php
> +        $imageFile = $form['image']->getData();
Je pense qu'il serait plus judicieux de faire passer les "data" en paramètre plutot que de lier ton persist à un objet formulaire

2020-11-06 10:15 UTC, Jduret commented on src/Service/Trick/Manager/TrickManager.php
> +            $trick->setImage($filename);
Quel différence entre `setImage` et `addImage` ? Les 2 manipulent les mêmes images ou `setImage` manipule l'image principal du trick et `addImage` gère les autres ?

2020-11-06 10:47 UTC, Jduret requested changes
Beau travail de refactorisation du controller. 
Par contre je ne vois aucun test unitaire de ton TrickManager... 🤔

2020-11-06 10:47 UTC, Jduret commented on src/Service/Trick/Manager/TrickManager.php
> +        foreach ($this->originalImages as $key => $originalImage) {
FYI : pas besoin de faire `$key=>$originalImage` si `$key` ne te sers à rien

2020-11-06 10:47 UTC, Jduret commented on src/Service/Trick/Manager/TrickManager.php
> +        }
Faire ça dans une méthode dédiée
```php
/** 
 * @description Permet de filtrer les images supprimées puis de la supprimer
 * @return array La liste des images supprimées
 */
protected function removeDeletedImages($originalImages, $trickImages)
{
    return array_map([$this, "removeImage"], array_filter(
        $originalImages,
        //array_filter ne garder que les élements où la fonction retourne VRAI
        function($imageData) use($trickImages) {
            return false === $trickImages->contains($imageData['image_object']);
        }
    ));
}

protected function removeImage($imageData)
{
    $this->fileUploader->remove($imageData['image_object']);
    return $imageData;
}
```

Attention, j'ai écrit ça directement dans github pour montrer une idée basé sur le "fonctional programming". Il peut contenir des erreurs

2020-11-06 10:47 UTC, Jduret commented on src/Form/ImageType.php
> +            function ($TEST) {
Je suis preneur d'une explication de cette variable `$TEST`

2020-11-06 15:09 UTC, Sp4tz7 commented on src/Service/Trick/Manager/TrickManager.php
> +            $trick->setImage($filename);
SetImage() définit l'image principale
SetImages() définit une collection d'images à l'objet Trick
addImage() ajoute un objet image à la collection images de l'objet Trick

2020-11-06 15:12 UTC, Sp4tz7 commented on src/Service/Trick/Manager/TrickManager.php
> +        foreach ($this->originalImages as $key => $originalImage) {
C'est juste... je l'avais utilisé avant puis supprimé. J'ai juste oublié le paramètre.

je corrige...

2020-11-06 15:14 UTC, Sp4tz7 commented on src/Form/ImageType.php
> +            function ($TEST) {
C'est une coquille 🤣

2020-11-09 20:30 UTC, Jduret commented on src/Service/Trick/Manager/TrickManager.php
> +            $trick->setImage($filename);
Alors dans ce cas, le nommage n'est pas très clair. Je te mets une idée mais tu peux trouver mieux surement :
- setMainImage
- setImages (si la main image correspond à l'image 0 de ta collection)
- setRemainingImages (ou quelque chose du genre si la main image n'est pas dedans)
- addImage ou addRemainingImage

En espérant que tu auras compris l'idée

2020-11-12 13:16 UTC, Sp4tz7 commented on src/Service/Trick/Manager/TrickManager.php
> +            $trick->setImage($filename);
Oui, effectivement. En fait c'est le make:entity de symfony qui a créé automatiquement ces fonctions et je n'ai pas pensé à les changer.

2020-11-12 20:33 UTC, Sp4tz7 commented on src/Service/Trick/Manager/TrickManager.php
> +        $imageFile = $form['image']->getData();
Ok, bonne idée. Merci je corrige.

2020-11-12 20:47 UTC, Sp4tz7 commented on src/Service/Trick/Manager/TrickManager.php
> +        }
Ok. Je verrai pour implémenter cette idée dans une prochaine release.

2020-11-17 09:45 UTC, merged